'use client'

import { useMemo, useState, useEffect } from 'react'
import {
  X,
  Thermometer,
  Droplets,
  Wind,
  CloudLightning,
  MapPin,
  Users,
  Download,
  Activity,
  TrendingUp,
  Plane,
  Satellite,
  ShieldAlert,
  AlertTriangle,
  BrainCircuit,
  Cpu
} from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import type { Country } from '@/lib/dashboard-data'
import { riskLevelConfig } from '@/lib/dashboard-data'
import { fetchLiveMarket, fetchAIPrediction } from '@/lib/api'

export default function CountryPanel({ country, onClose }: any) {
  const [localGold, setLocalGold] = useState<number | null>(null);
  const [goldUnit, setGoldUnit] = useState<'OZ'|'G'|'TOLA'|'KG'>('OZ');
  const [realWeather, setRealWeather] = useState<any>(null);

  useEffect(() => {
    if (country) {
      setRealWeather(null);
      fetchLiveMarket().then((market: any) => {
        if (market && market.localizedGold) {
          setLocalGold(market.localizedGold[country.code] || market.goldPriceUSD);
        }
      });
      // 100% Free, Open-Source live weather via Open-Meteo API
      fetch(`https://api.open-meteo.com/v1/forecast?latitude=${Math.round(country.lat * 100) / 100}&longitude=${Math.round(country.lng * 100) / 100}&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code`)
        .then(res => res.json())
        .then(data => {
          if (data.current) {
            const code = data.current.weather_code;
            setRealWeather({
              temp: Math.round(data.current.temperature_2m),
              wind: Math.round(data.current.wind_speed_10m),
              humidity: Math.round(data.current.relative_humidity_2m),
              condition: code > 50 ? 'Precipitation' : code > 0 ? 'Cloudy' : 'Clear'
            });
          }
        }).catch(() => {});
    }
  }, [country?.code]);

  if (!country) return <EmptyPanel />

  const riskConfig = riskLevelConfig[country.riskLevel]

  const goldMultipliers = {
    'OZ': 1,
    'G': 1 / 31.1035,
    'TOLA': 1 / 2.666,
    'KG': 32.1507
  };

  const currentLocalGoldValue = localGold ? (localGold * goldMultipliers[goldUnit]) : null;

  const handleDownloadReport = () => {
    if (!country) return;
    const w = realWeather || country.weather;
    const analysisText = document.getElementById('ai-analysis-text')?.innerText || 'Surveillance baseline active. No deep analysis generated yet.';
    
    const content = `GEO-PULSE SENTINEL - DECLASSIFIED INTEL REPORT
==============================================
TARGET: ${country.name} (${country.code})
REGION: ${country.region}
COORDINATES: ${country.lat.toFixed(4)} N, ${country.lng.toFixed(4)} E
THREAT LEVEL: ${country.riskLevel.toUpperCase()} (Score: ${country.riskScore})

--- METEOROLOGICAL DATA ---
Temperature: ${w.temp}°C
Condition:   ${w.condition}
Wind Speed:  ${w.wind} km/h
Humidity:    ${w.humidity}%

--- STRATEGIC ANALYSIS ---
${analysisText}

---
Generated by: GeoPulse Sentinel System
Timestamp: ${new Date().toISOString()}
Data Sources: OpenStreetMap, Open-Meteo (Strict Open-Source FOSS Compliance)
`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `INTEL_BRIEF_${country.code}_${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.aside 
      initial={{ width: 0, opacity: 0 }}
      animate={{ width: 288, opacity: 1 }}
      exit={{ width: 0, opacity: 0 }}
      className="w-72 shrink-0 bg-[var(--bg-secondary)] border-l border-[var(--surface-border)] flex flex-col overflow-hidden"
    >
      <div className="h-10 flex items-center justify-between px-3 border-b border-[var(--surface-border)] shrink-0">
        <div className="flex items-center gap-2">
          <Activity className="w-3.5 h-3.5 text-[var(--blue-bright)] animate-pulse" />
          <span className="text-[10px] font-display font-semibold text-[var(--blue-bright)] tracking-[0.2em]">INTEL REPORT</span>
        </div>
        <div className="flex items-center gap-1">
          <button onClick={handleDownloadReport} className="w-6 h-6 flex items-center justify-center text-[var(--text-muted)] hover:text-[var(--blue-bright)] bg-transparent hover:bg-[var(--bg-elevated)] rounded transition-all" title="Download Declassified Intel Brief (TXT)">
            <Download className="w-3.5 h-3.5" />
          </button>
          <div className="w-px h-3 bg-[var(--surface-border)] mx-1" />
          <button onClick={onClose} className="w-6 h-6 flex items-center justify-center text-[var(--text-muted)] hover:text-[var(--status-critical)] bg-transparent hover:bg-[var(--status-critical)]/10 rounded transition-all">
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto">
        <motion.div layout className="p-4 border-b border-[var(--surface-border)]">
          <div className="flex items-center gap-3 mb-3">
            <span className="text-3xl">{country.flag}</span>
            <div>
              <h2 className="text-[18px] font-display font-bold text-[var(--text-primary)] tracking-wide">{country.name}</h2>
              <div className="flex items-center gap-2 mt-0.5">
                <span className="text-[10px] font-mono text-[var(--text-muted)]">{country.code}</span>
                <span className="text-[10px] font-mono text-[var(--text-muted)]">|</span>
                <span className="text-[10px] font-mono text-[var(--text-muted)]">{country.region}</span>
              </div>
            </div>
          </div>
          <RiskMeter score={country.riskScore} level={country.riskLevel} config={riskConfig} />
        </motion.div>

        <div className="flex flex-col">
          <AIAnalysisSection countryCode={country.code} />
          <DataSection title="WEATHER CONDITIONS" icon={<CloudLightning className="w-3 h-3" />}>
            <div className="grid grid-cols-2 gap-2">
              <DataTile icon={<Thermometer className="w-3 h-3 text-sentinel-amber" />} label="TEMP" value={`${(realWeather || country.weather).temp}°C`} />
              <DataTile icon={<Droplets className="w-3 h-3 text-sentinel-cyan" />} label="HUMIDITY" value={`${(realWeather || country.weather).humidity}%`} />
              <DataTile icon={<Wind className="w-3 h-3 text-muted-foreground" />} label="WIND" value={`${(realWeather || country.weather).wind} km/h`} />
              <DataTile icon={<CloudLightning className="w-3 h-3 text-sentinel-cyan" />} label="STATUS" value={(realWeather || country.weather).condition} small />
            </div>
          </DataSection>
          
          <DataSection title="KEY INDICATORS" icon={<TrendingUp className="w-3 h-3" />}>
            <div className="grid grid-cols-2 gap-2 mb-2">
              <IndicatorCard icon={<TrendingUp className="w-3.5 h-3.5 text-sentinel-gold" />} label="GOLD" value={currentLocalGoldValue ? currentLocalGoldValue.toLocaleString(undefined, { maximumFractionDigits: 1 }) : '...'} color="#FFD700" />
              <IndicatorCard icon={<Plane className="w-3.5 h-3.5 text-sentinel-cyan" />} label="FLIGHTS" value={country.flightDensity.toLocaleString()} color="#00E5FF" />
            </div>
            
            <div className="flex z-10 w-full p-1 bg-[var(--bg-elevated)] border border-[var(--surface-border)] rounded shadow-inner gap-1">
              {(['OZ', 'G', 'TOLA', 'KG'] as const).map(u => (
                <button
                  key={u}
                  onClick={() => setGoldUnit(u)}
                  className={`flex-1 flex justify-center text-[10px] font-mono py-1 rounded transition-colors ${goldUnit === u ? 'bg-[var(--blue-accent)] text-white font-bold' : 'text-[var(--text-muted)] hover:text-white hover:bg-[var(--surface-line)]'}`}
                >
                  {u}
                </button>
              ))}
            </div>
          </DataSection>
        </div>
      </div>
    </motion.aside>
  )
}

function AIAnalysisSection({ countryCode }: { countryCode: string }) {
  const [analyzing, setAnalyzing] = useState(true)
  const [prediction, setPrediction] = useState<any>(null)

  useEffect(() => {
    setAnalyzing(true)
    fetchAIPrediction(countryCode).then(data => {
      setPrediction(data)
      setAnalyzing(false)
    }).catch(() => setAnalyzing(false))
  }, [countryCode])

  return (
    <DataSection title="AI MARKET & THREAT ANALYZER" icon={<BrainCircuit className="w-3 h-3" />}>
      <div className="relative p-3 rounded bg-[var(--bg-elevated)] border border-[var(--surface-border)] overflow-hidden">
        {analyzing ? (
          <div className="flex flex-col items-center justify-center py-4 gap-2">
            <Cpu className="w-5 h-5 text-[var(--blue-bright)] animate-pulse" />
            <span className="text-[10px] font-mono text-[var(--blue-bright)] tracking-widest animate-pulse">PROCESSING NEURAL ANALYSIS...</span>
          </div>
        ) : (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex flex-col gap-2">
            <div className="flex items-start gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-[var(--blue-bright)] mt-1 shrink-0 shadow-[0_0_8px_var(--blue-glow)]" />
              <p id="ai-analysis-text" className="text-[11px] font-sans text-[var(--text-secondary)] leading-[1.6]">
                {prediction?.analysis || "Unable to acquire neural prediction data. Surveillance baseline active."}
              </p>
            </div>
            <div className="flex justify-between items-center mt-2 pt-2 border-t border-[var(--surface-border)]">
              <span className="text-[9px] font-mono text-[var(--text-muted)]">CONFIDENCE: {prediction?.confidence || 'N/A'}%</span>
              <span className="text-[9px] font-mono text-[var(--blue-bright)]">MODEL: {prediction?.model || 'FALLBACK'}</span>
            </div>
          </motion.div>
        )}
      </div>
    </DataSection>
  )
}

function EmptyPanel() {
  return (
    <aside className="w-72 shrink-0 bg-[var(--bg-secondary)] border-l border-[var(--surface-border)] flex flex-col items-center justify-center p-6">
      <div className="flex flex-col items-center gap-3 text-center">
        <div className="w-16 h-16 rounded-full border border-[var(--surface-border)] flex items-center justify-center">
          <MapPin className="w-6 h-6 text-[var(--text-muted)]/40" />
        </div>
        <span className="text-xs font-display text-[var(--text-muted)] tracking-wider">SELECT A COUNTRY</span>
        <span className="text-[10px] font-sans text-[var(--text-muted)]/60 max-w-[180px]">
          Click on any marker on the map to view intelligence data
        </span>
      </div>
    </aside>
  )
}

// Reuse other small components exactly
function RiskMeter({ score, level, config }: any) {
  return (
    <div className="relative p-3 rounded bg-[var(--bg-elevated)] border border-[var(--surface-border)]" style={{ borderColor: `${config.color}30` }}>
      <div className="flex items-center justify-between mb-2">
         <span className="text-[10px] font-mono text-[var(--text-muted)] tracking-[0.1em]">THREAT</span>
         <span className="text-[10px] font-mono font-bold px-2 py-0.5 rounded" style={{ color: config.color, background: `${config.color}15` }}>{config.label}</span>
      </div>
      <div className="relative h-1.5 rounded-full bg-[var(--surface-line)] overflow-hidden mb-1.5">
        <motion.div initial={{ width: 0 }} animate={{ width: `${score}%` }} transition={{ duration: 1.5, ease: "easeOut" }} className="absolute inset-y-0 left-0 rounded-full" style={{ background: config.color, boxShadow: config.glow }} />
      </div>
    </div>
  )
}

function DataSection({ title, icon, children }: any) {
  return (
    <div className="p-3 border-b border-[var(--surface-border)]">
      <div className="flex items-center gap-1.5 mb-2.5">
        <span className="text-[var(--blue-bright)]">{icon}</span>
        <span className="text-[11px] font-display font-bold text-[var(--blue-bright)] tracking-[0.15em]">{title}</span>
      </div>
      {children}
    </div>
  )
}

function DataTile({ icon, label, value, small }: any) {
  return (
    <div className="flex items-center gap-2 p-2 rounded bg-sentinel-surface-2/50 border border-border">
      {icon}
      <div className="flex flex-col">
        <span className="text-[8px] font-mono text-muted-foreground/60">{label}</span>
        <span className={`font-mono text-foreground ${small ? 'text-[10px]' : 'text-xs'}`}>{value}</span>
      </div>
    </div>
  )
}

function IndicatorCard({ icon, label, value, color }: any) {
  return (
    <div className="flex flex-col items-center gap-1 p-2.5 rounded bg-sentinel-surface-2/50 border border-border">
      {icon}
      <span className="text-[8px] font-mono text-muted-foreground/60 tracking-wider">{label}</span>
      <span className="text-xs font-mono font-semibold" style={{ color }}>{value}</span>
    </div>
  )
}
